title: Billy Zhao
description: Personal website and portfolio
repository: billlyzhaoyh/billlyzhaoyh.github.io
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false
